name: Update Copyright Year
on:
  schedule:
    - cron: '0 0 1 1 *' # Runs every year on January 1st
  workflow_dispatch: # Allow manual triggering

jobs:
  update-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update year in README
        run: |
          sed -i "s/© [0-9]\{4\}/© $(date +%Y)/g" .github/profile/README.md

      - name: Commit and push changes
        if: contains(steps.update-year.outputs.result, 'changed')
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update copyright year to $(date +%Y)"
          git push