name: Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs every year on January 1st
  workflow_dispatch: # Allow manual triggering

jobs:
  update-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update year in README
        run: |
          FILE_PATH="profile/README.md"
          sed -i "s/© [0-9]\{4\}/© $(date +%Y)/g" "$FILE_PATH"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update copyright year to $(date +%Y)"
          git push
